spring.application.name=bidding-engine


spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties[spring.json.add.type.headers]=false

spring.kafka.consumer.group-id=bidding-engine
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties[spring.json.value.default.type]=bidding_engine.model.BidAcceptedEvent
spring.kafka.consumer.properties[spring.json.use.type.headers]=false

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/bidding_db
spring.r2dbc.username=pulsegrid
spring.r2dbc.password=pulsegrid